name: "Mirror docker containers"

on:
  # See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  docker:
    name: releases-by-docker
    runs-on: ubuntu-20.04

    steps:
      ################################################################################################
      ################################################################################################
      ################################################################################################
      # Aliyun ACR
      - name: Login Aliyun docker hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Mirror to ACR for node:slim
        run: |
          docker pull node:slim
          docker tag node:slim registry.cn-hangzhou.aliyuncs.com/ossrs/node:slim
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/node
          echo "Release ok, please see:"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/node/images"

      - name: Mirror to ACR for prom/prometheus
        run: |
          docker pull prom/prometheus
          docker tag prom/prometheus registry.cn-hangzhou.aliyuncs.com/ossrs/prometheus
          docker push --all-tags registry.cn-hangzhou.aliyuncs.com/ossrs/prometheus
          echo "Release ok, please see:"
          echo "  https://cr.console.aliyun.com/repository/cn-hangzhou/ossrs/prometheus/images"

      ################################################################################################
      ################################################################################################
      ################################################################################################
      # Tencent TCR
      - name: Login Tencent docker hub
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: "${{ secrets.TCR_USERNAME }}"
          password: "${{ secrets.TCR_PASSWORD }}"

      - name: Mirror to TCR for node:slim
        run: |
          docker pull node:slim
          docker tag node:slim ccr.ccs.tencentyun.com/ossrs/node:slim
          docker push --all-tags ccr.ccs.tencentyun.com/ossrs/node
          echo "Release ok, please see:"
          echo "  https://console.cloud.tencent.com/tcr/repository/details/ccr/ossrs/node/1"

      - name: Mirror to TCR for prom/prometheus
        run: |
          docker pull prom/prometheus
          docker tag prom/prometheus ccr.ccs.tencentyun.com/ossrs/prometheus
          docker push --all-tags ccr.ccs.tencentyun.com/ossrs/prometheus
          echo "Release ok, please see:"
          echo "  https://console.cloud.tencent.com/tcr/repository/details/ccr/ossrs/prometheus/1"