name: Test for commits

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test for commits
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See https://github.com/actions/setup-node
      - name: Setup the npm node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            mgmt/package-lock.json
            platform/package-lock.json
            platform/ui/package-lock.json
            releases/package-lock.json
            ffmpeg/package-lock.json
            tecent/package-lock.json

      - name: Install and build
        run: |
          make build

      - name: Test by jest
        run: |
          make test

