name: Test for commits

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test for commits
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # See https://github.com/actions/setup-node
      - name: Setup the npm node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            ui/package-lock.json

      # See https://github.com/actions/setup-go
      - name: Setup the Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.16.0'

      - name: Test by jest and Go
        run: |
          make -j && make test -j

